// This file is auto-generated by scripts/generate-blog-manifest.js.
// Do not edit it manually.

export const blogPosts = [
  {
    slug: "hello-world",
    title: "Hello, World",
    date: "2025-01-01",
    summary: "Welcome to my blog! A sample post demonstrating lists and LaTeX rendering.",
    tags: ["Getting Started","Demo","Blog"],
    readingTime: 2,
    featured: false,
    lastModified: "",
    fileName: "hello-world.mdx",
    load: () => import("./hello-world.mdx"),
  },
  {
    slug: "mathematics-with-latex",
    title: "Beautiful Mathematics with LaTeX",
    date: "2025-10-11",
    summary: "Demonstrating beautiful mathematical equations using LaTeX rendering in blog posts.",
    tags: ["mathematics","latex","demo","equations"],
    readingTime: 5,
    featured: false,
    lastModified: "",
    fileName: "mathematics-with-latex.mdx",
    load: () => import("./mathematics-with-latex.mdx"),
  },
  {
    slug: "quantum-fundamentals-single-multiple-qubits",
    title: "Quantum Fundamentals: Single and Multiple Qubit Systems",
    date: "2025-10-08",
    summary: "A comprehensive exploration of quantum computing fundamentals, covering complex numbers, Hilbert spaces, superposition, entanglement, and practical implementations with Qiskit.",
    tags: ["quantum computing","physics","qiskit","research","seminar"],
    readingTime: 25,
    featured: true,
    lastModified: "",
    fileName: "quantum-fundamentals-single-multiple-qubits.mdx",
    load: () => import("./quantum-fundamentals-single-multiple-qubits.mdx"),
  }
].sort((a, b) => (b.date || '').localeCompare(a.date || ''));

const blogPostMap = new Map(blogPosts.map((post) => [post.slug, post]));

export function getBlogPostEntry(slug) {
  return blogPostMap.get(slug) || null;
}

export function getRecentBlogPosts(limit = 3) {
  return blogPosts.slice(0, limit);
}
